// src/app/player/player.component.ts
import {
  Component,
  OnInit,
  ViewChild,
  ElementRef,
  OnDestroy,
  AfterViewInit,
  HostListener,
  ChangeDetectorRef
} from '@angular/core';
import { DashboardService } from './../dashboard/service/dashboard.service';
import * as $ from 'jquery';
import * as CommonConstant from '../shared/constant/common.constant';
import { PlayList } from './model/playlist.model';
import { CourseModel } from '../dashboard/course/model/course.model';
import { CurrentPlayListModel } from './model/current-playlist.model';
import { PLAYLIST_PLAY_NEXT } from '../shared/constant/common.constant';
import { Router } from '@angular/router';
import { TimeoutDialogService } from '../auth/timeout/timeout-dialog.service';
import { PlayerDataService } from './service/player-data.service';
import { ResumePlayerModel } from './model/resume-player.model';
import { BeforeUnload } from '../util/unload/service/unload.service';
import { Observable } from 'rxjs/Observable';

@Component({
  selector: 'app-player',
  templateUrl: './player.component.html',
  styleUrls: ['./player.component.css']
})
export class PlayerComponent
  implements OnInit, OnDestroy, BeforeUnload, AfterViewInit {
  constructor(
    private dashboardService: DashboardService,
    private router: Router,
    private timeoutDialogService: TimeoutDialogService,
    private playerDataService: PlayerDataService,
    private elementRef: ElementRef,
    private cdRef: ChangeDetectorRef
  ) {}
  playList: PlayList[];
  videoPlayer: HTMLVideoElement;
  currentPlayListModel: CurrentPlayListModel;
  currentVideoCounter: number = 0;
  globalVideoCounter: number = 0;
  fadeOutTimer;
  initToggler = false;
  playerVolume: number = 0;
  playbackRate: number = 1;
  currentVolumeBarFill: string;
  totalVideoDuration: number;
  btnFileBeingViewedId: string;
  iconFileBeingViewedId: string;
  currentFileName: string = '';
  ngOnInit() {
    this.timeoutDialogService.pauseOrContinueTimeOut(true);
    this.init();
  }
  ngOnDestroy(): void {}
  beforeunload(): boolean | Observable<boolean> | Promise<boolean> {
    $('#headerNav').show();
    this.populateResumeFromTimeOnExit();
    this.timeoutDialogService.pauseOrContinueTimeOut(false);
    return true;
  }
  init() {
    this.initPlayList();
    this.initCoursePlayListModel();
    this.initEventListeners();
  }
  ngAfterViewInit(): void {
    this.resumeFromTime();
    this.hideHeaderNav();
    this.fadeVideoControls();
    this.styleDropupRate();
    //this.populateCurrentFileNamePostInit();
    this.cdRef.detectChanges();
  }
  hideHeaderNav() {
    $('#headerNav').hide();
  } // @HostListener('window:unload', ['$event'])
  // unloadHandler(event) {
  //   //add the logic to save resume time and other info post db implementation
  // }
  // @HostListener('window:beforeunload', ['$event'])
  // beforeUnloadHander(event) {
  //   //add the logic to save resume time and other info post db implementation
  // }
  initCoursePlayListModel(resumePlayerInfo?: ResumePlayerModel) {
    if (this.currentPlayListModel == undefined) {
      this.currentPlayListModel = new CurrentPlayListModel();
    }
    if (resumePlayerInfo != undefined) {
      this.currentPlayListModel.playListIndex = resumePlayerInfo.playListIndex;
      this.currentPlayListModel.fileIndex = resumePlayerInfo.fileIndex;
    }
    this.currentPlayListModel.fileLocation = this.getFileLocationFromPlayList(
      this.currentPlayListModel.playListIndex,
      this.currentPlayListModel.fileIndex
    );
  }
  initEventListeners() {
    var self = this;
    this.videoPlayer = document.querySelector('video');
    this.playerVolume = this.videoPlayer.volume;
    $('#seekbar')[0].oninput = function() {
      var seekBarVal = $('#seekbar').val();
      var vidTime = self.videoPlayer.duration * (seekBarVal / 100);
      self.videoPlayer.currentTime = vidTime;
    };
    $('#seekbar').on('change mousemove', function() {
      var val =
        ($(this).val() - $(this).attr('min')) /
        ($(this).attr('max') - $(this).attr('min'));
      $(this).css(
        'background-image',
        '-webkit-gradient(linear, left top, right top, ' +
          'color-stop(' +
          val +
          ', #3f51b5), ' +
          'color-stop(' +
          val +
          ', #818181)' +
          ')'
      );
    }); //init the minimum volumeFiller
    $('#volumeControl').css(
      'background-image',
      '-webkit-gradient(linear, 0% 0%, 100% 0%, color-stop(0.353535, rgb(63, 81, 181)),' +
        'color-stop(0.353535, rgb(129, 129, 129)))'
    );
    $('#volumeControl').on('change input click', function() {
      if (self.videoPlayer.muted) {
        self.controlMuteOrUnmute(CommonConstant.PLAYLIST_VOLUME_UNMUTE);
      }
      if ($(this).val() < 35) {
        $(this).val(36);
        return false;
      }
      var val =
        ($(this).val() - $(this).attr('min')) /
        ($(this).attr('max') - $(this).attr('min'));
      $(this).css(
        'background-image',
        '-webkit-gradient(linear, left top, right top, ' +
          'color-stop(' +
          val +
          ', #3f51b5), ' +
          'color-stop(' +
          val +
          ', #818181)' +
          ')'
      ); //restrict volumecontrol to go beyond the button icon
      //console.log('Before: ' + self.videoPlayer.volume);
      self.videoPlayer.volume = $(this).val() / 100; //console.log('After: ' + self.videoPlayer.volume);
    });
    $('#videoPlayer').on('click', function(e) {
      self.controlAction(CommonConstant.PLAYLIST_PLAY_PAUSE);
    });
    this.videoPlayer.addEventListener('ended', function(e) {
      self.autoPlayNext();
    });
    this.videoPlayer.ontimeupdate = function() {
      if (!isNaN(self.videoPlayer.duration)) {
        var percentage =
          self.videoPlayer.currentTime / self.videoPlayer.duration * 100;
        $('#seekbar')
          .val(percentage)
          .change();
        var currentTime: number = self.videoPlayer.currentTime;
        var totalDuration: number = self.videoPlayer.duration;
        $('#seekbarTimer').text(
          self.formatTime(currentTime) + '/' + self.formatTime(totalDuration)
        );
      }
    };
  }
  @HostListener('document:keyup', ['$event'])
  onKeypressEventHandler(event) {
    var self = this;
    switch (event.keyCode) {
      case 32: // space
        //handle the play pause if the playPause btn is focused
        if (document.activeElement.id == 'btnPlayPause') {
          $('#btnPlayPause').click();
          break;
        }
        self.controlAction(CommonConstant.PLAYLIST_PLAY_PAUSE);
        document.activeElement.classList.add('focusable-thing');
        break;
      case 37: // left arrow
        self.controlAction(CommonConstant.PLAYLIST_PLAY_PREVIOUS);
        break;
      case 39: // right arrow
        self.controlAction(CommonConstant.PLAYLIST_PLAY_NEXT);
        break;
      default:
        return;
    }
  }
  initPlaying(currentPlayListModel: CurrentPlayListModel) {
    this.currentPlayListModel = currentPlayListModel;
    this.play(currentPlayListModel.fileLocation);
    this.initToggler = true;
    this.controlPlayOrPause(CommonConstant.PLAYLIST_PLAY);
  }
  play(fileLocation: string) {
    this.videoPlayer.src = fileLocation;
    this.videoPlayer.playbackRate = this.playbackRate;
    this.videoPlayer.play(); //push the details of fileContent metadata into the playlist
    this.populateAndPublishFileContentMetaData();
    this.styleFileBeingViewed();
    this.populateCurrentFileNamePostInit();
  }
  populateFileContentMetaData() {
    let playListIndex =
      this.currentPlayListModel == undefined
        ? 0
        : this.currentPlayListModel.playListIndex;
    let fileIndex =
      this.currentPlayListModel == undefined
        ? 0
        : this.currentPlayListModel.fileIndex;
    let currentVideoDuration = this.videoPlayer.duration;
    this.playList[playListIndex].fileContent[
      fileIndex
    ].totalDuration = currentVideoDuration;
  }
  populateResumeFromTimeOnExit() {
    let playListIndex =
      this.currentPlayListModel == undefined
        ? 0
        : this.currentPlayListModel.playListIndex;
    let fileIndex =
      this.currentPlayListModel == undefined
        ? 0
        : this.currentPlayListModel.fileIndex;
    this.playList[playListIndex].fileContent[
      fileIndex
    ].resumeFromTime = this.videoPlayer.currentTime;
    this.dashboardService.setCoursePlayListData(this.playList);
    let resumeCourseInfo = new ResumePlayerModel();
    resumeCourseInfo.fileIndex = fileIndex;
    resumeCourseInfo.playListIndex = playListIndex;
    resumeCourseInfo.resumeFromTime = this.videoPlayer.currentTime;
    resumeCourseInfo.playerSpeed = this.videoPlayer.playbackRate;
    this.dashboardService.addResumeCourseInfo(resumeCourseInfo);
  }
  populateCoursePlayListFilePlayedCompletely() {
    let playListIndex =
      this.currentPlayListModel == undefined
        ? 0
        : this.currentPlayListModel.playListIndex;
    let fileIndex =
      this.currentPlayListModel == undefined
        ? 0
        : this.currentPlayListModel.fileIndex;
    this.playList[playListIndex].fileContent[fileIndex].played = true;
  }
  getCourseListFilePlayedCompletelyInd() {
    let playListIndex =
      this.currentPlayListModel == undefined
        ? 0
        : this.currentPlayListModel.playListIndex;
    let fileIndex =
      this.currentPlayListModel == undefined
        ? 0
        : this.currentPlayListModel.fileIndex;
    return this.playList[playListIndex].fileContent[fileIndex].played;
  }
  populateAndPublishFileContentMetaData() {
    this.populateFileContentMetaData();
    this.dashboardService.setCoursePlayListData(this.playList);
  }
  populateResumeFromTime() {
    let playListIndex =
      this.currentPlayListModel == undefined
        ? 0
        : this.currentPlayListModel.playListIndex;
    let fileIndex =
      this.currentPlayListModel == undefined
        ? 0
        : this.currentPlayListModel.fileIndex;
    this.playList[playListIndex].fileContent[
      fileIndex
    ].resumeFromTime = this.videoPlayer.currentTime;
  }
  resumeFromTime() {
    let resumePlayerInfo: ResumePlayerModel = this.dashboardService.getResumeCourseInfo();
    if (resumePlayerInfo.resumeFromTime != undefined) {
      this.videoPlayer.currentTime = resumePlayerInfo.resumeFromTime;
      this.playbackRate = resumePlayerInfo.playerSpeed;
      this.changePlayBackRate(this.playbackRate);
      this.initCoursePlayListModel(resumePlayerInfo);
      this.play(
        this.getFileLocationFromPlayList(
          resumePlayerInfo.playListIndex,
          resumePlayerInfo.fileIndex
        )
      );
    }
  }
  controlPlayOrPause(type: string) {
    if (type == CommonConstant.PLAYLIST_PLAY) {
      this.showControlActionPerformed(type, false);
      this.togglePlayOrPause(type);
    } else if (type == CommonConstant.PLAYLIST_PAUSE) {
      this.showControlActionPerformed(type, true);
      this.togglePlayOrPause(type);
    }
  }
  controlMuteOrUnmute(type: string) {
    this.toggleMuteOrUnmute(type);
    this.showControlActionPerformed(type, false);
  }
  controlAction(type: string) {
    let isVideoPaused = false;
    if (this.videoPlayer) {
      isVideoPaused = this.videoPlayer.paused;
    }
    if (type === CommonConstant.PLAYLIST_PLAY_PAUSE) {
      if (this.videoPlayer.paused) {
        type = CommonConstant.PLAYLIST_PLAY;
        this.showControlActionPerformed(CommonConstant.PLAYLIST_PLAY, false);
      } else {
        type = CommonConstant.PLAYLIST_PAUSE;
        this.showControlActionPerformed(CommonConstant.PLAYLIST_PAUSE, true);
      }
      this.togglePlayOrPause(type);
    } else if (type === CommonConstant.PLAYLIST_PLAY_NEXT) {
      if (!isVideoPaused) {
        this.showControlActionPerformed(
          CommonConstant.PLAYLIST_PLAY_NEXT,
          false
        );
      }
      this.forwardCurrentTime();
    } else if (type === CommonConstant.PLAYLIST_PLAY_PREVIOUS) {
      if (!isVideoPaused) {
        this.showControlActionPerformed(
          CommonConstant.PLAYLIST_PLAY_PREVIOUS,
          false
        );
      }
      this.rewindCurrentTime();
    } else if (type === CommonConstant.PLAYLIST_VOLUME) {
      if (this.videoPlayer.muted) {
        type = CommonConstant.PLAYLIST_VOLUME_UNMUTE;
        this.showControlActionPerformed(
          CommonConstant.PLAYLIST_VOLUME_UNMUTE,
          false
        );
      } else {
        type = CommonConstant.PLAYLIST_VOLUME_MUTE;
        this.showControlActionPerformed(
          CommonConstant.PLAYLIST_VOLUME_MUTE,
          false
        );
      }
      this.toggleMuteOrUnmute(type);
    }
  }
  togglePlayOrPause(type: string) {
    if (type != undefined) {
      if (type === CommonConstant.PLAYLIST_PLAY) {
        this.videoPlayer.play();
        $('#iconPlayPause').text('pause');
      } else if (type === CommonConstant.PLAYLIST_PAUSE) {
        this.videoPlayer.pause();
        $('#iconPlayPause').text('play_arrow');
      }
    }
  }
  toggleMuteOrUnmute(type: string) {
    if (type != undefined) {
      if (type === CommonConstant.PLAYLIST_VOLUME_MUTE) {
        this.videoPlayer.muted = true;
        $('#iconMuteUnmute').text('volume_off');
        $('#btnVolume').toggleClass('btn__volume-mute');
        this.currentVolumeBarFill = $('#volumeControl').css('background-image');
        console.log('this.currentVolumeBarFill', this.currentVolumeBarFill);
        $('#volumeControl').css({
          'background-image': 'none'
        });
      } else if (type === CommonConstant.PLAYLIST_VOLUME_UNMUTE) {
        this.videoPlayer.muted = false;
        $('#iconMuteUnmute').text('volume_up');
        $('#btnVolume').toggleClass('btn__volume-mute');
        $('#volumeControl').css({
          'background-image': this.currentVolumeBarFill
        });
      }
    }
  }
  rewindCurrentTime() {
    this.videoPlayer.currentTime += -5;
  }
  changePlayBackRate(rate: number) {
    this.videoPlayer.playbackRate = rate;
    this.playbackRate = rate;
    $('#playBackSpeedBtn').text(rate + 'x');
    this.styleDropupRate();
  }
  styleDropupRate() {
    var rate = this.videoPlayer.playbackRate;
    $('.rate-dropup').each(function() {
      var dropupRate = $(this)
        .text()
        .replace('x', '');
      if (rate == dropupRate) {
        $(this).css('background', '#3f51b5');
      } else {
        $(this).css('background', '#818181');
      }
    });
  }
  forwardCurrentTime() {
    this.videoPlayer.currentTime += 5;
  }
  toggleFullScreen() {
    $('#videoPlayer').toggleClass('video__fullscreen--maxheight'); //this.videoPlayer.classList.toggle('video__fullscreen--maxheight');
    var self = this;
    var fullscreenElement =
      document.fullscreenElement || document.webkitFullscreenElement;
    if (fullscreenElement) {
      $('#iconFullScreen').text('fullscreen');
      self.exitFullscreen();
    } else {
      $('#iconFullScreen').text('fullscreen_exit');
      self.launchIntoFullscreen(
        document.getElementById('videoPlayerContainer')
      );
    }
  }
  launchIntoFullscreen(element) {
    if (element.requestFullscreen) {
      element.requestFullscreen();
    } else if (element.mozRequestFullScreen) {
      element.mozRequestFullScreen();
    } else if (element.webkitRequestFullscreen) {
      element.webkitRequestFullscreen();
    } else if (element.msRequestFullscreen) {
      element.msRequestFullscreen();
    }
  }
  exitFullscreen() {
    if (document.exitFullscreen) {
      document.exitFullscreen();
    } else if (document.webkitExitFullscreen) {
      document.webkitExitFullscreen();
    }
  }
  playNext() {
    var self = this;
    let fileLocation = self.getPrevOrNextFileLocation(
      CommonConstant.PLAYLIST_PLAY_NEXT
    );
    if (self.currentPlayListModel.fileLocation != fileLocation) {
      self.play(fileLocation);
    }
  }
  autoPlayNext() {
    var self = this;
    self.playNext();
    self.populateCoursePlayListFilePlayedCompletely();
  }
  playPrev() {
    let fileLocation = this.getPrevOrNextFileLocation(
      CommonConstant.PLAYLIST_PLAY_PREVIOUS
    );
    if (this.currentPlayListModel.fileLocation != fileLocation) {
      this.play(fileLocation);
    }
  }
  showControlActionPerformed(type: string, disableFadeOut: boolean) {
    $('#controlActionPerfContainer').removeClass('hide fadeout__action');
    if (!disableFadeOut) {
      setTimeout(function() {
        $('#controlActionPerfContainer').addClass('fadeout__action');
      }, 200);
    }
    if (type === CommonConstant.PLAYLIST_PLAY) {
      $('#iconControlAction').text('play_arrow');
    } else if (type === CommonConstant.PLAYLIST_PAUSE) {
      $('#iconControlAction').text('pause');
    } else if (type === CommonConstant.PLAYLIST_PLAY_NEXT) {
      $('#iconControlAction').text('forward_5');
    } else if (type === CommonConstant.PLAYLIST_PLAY_PREVIOUS) {
      $('#iconControlAction').text('replay_5');
    } else if (type === CommonConstant.PLAYLIST_VOLUME_MUTE) {
      $('#iconControlAction').text('volume_off');
    } else if (type === CommonConstant.PLAYLIST_VOLUME_UNMUTE) {
      $('#iconControlAction').text('volume_up');
    }
  }
  getPrevOrNextFileLocation(type: string) {
    let playListIndex =
      this.currentPlayListModel == undefined
        ? 0
        : this.currentPlayListModel.playListIndex;
    let fileIndex =
      this.currentPlayListModel == undefined
        ? 0
        : this.currentPlayListModel.fileIndex;
    if (type === CommonConstant.PLAYLIST_PLAY_PREVIOUS) {
      if (fileIndex < 1) {
        if (playListIndex > 0) {
          playListIndex -= 1;
          fileIndex = this.playList[playListIndex].fileContent.length - 1;
          this.currentPlayListModel.playListIndex = playListIndex;
          this.currentPlayListModel.fileIndex = fileIndex;
        }
      } else {
        fileIndex -= 1;
        this.currentPlayListModel.fileIndex = fileIndex;
      }
    } else if (type === CommonConstant.PLAYLIST_PLAY_NEXT) {
      let fileContentLength =
        this.playList[playListIndex].fileContent.length - 1;
      let playListSize = this.playList.length - 1;
      if (fileIndex == fileContentLength) {
        if (playListIndex < playListSize) {
          playListIndex += 1;
          fileIndex = 0;
          this.currentPlayListModel.playListIndex = playListIndex;
          this.currentPlayListModel.fileIndex = fileIndex;
        }
      } else {
        fileIndex += 1;
        this.currentPlayListModel.fileIndex = fileIndex;
      }
    }
    return this.getFileLocationFromPlayList(playListIndex, fileIndex);
  }
  getFileLocationFromPlayList(playListIndex: number, fileIndex: number) {
    let playListIndexCounter: number = 0;
    let fileLocation = '';
    this.playList.some(function(playListItem, i) {
      playListItem.fileContent.some(function(fileItem, k) {
        if (playListIndex == i && fileIndex == k) {
          fileLocation = fileItem.fileLocation;
          return true;
        }
      });
      if (fileLocation == '') {
        return false;
      } else {
        return true;
      }
    });
    return fileLocation;
  }
  initPlayList() {
    if (this.dashboardService.getCourseData().length > 0) {
      var index = this.dashboardService.findCourseIndexFromDashboard(
        this.dashboardService.playCourseId,
        this.dashboardService.getCourseData()
      );
      this.playList = this.dashboardService.getCourseData()[
        index
      ].coursePlayList;
    }
  }
  togglePlayList() {
    $('.app-playlist').toggleClass('hide');
    if ($('#btnTogglePlayList').hasClass('toggle__playlist-close')) {
      if (!this.initToggler) {
        this.controlPlayOrPause(CommonConstant.PLAYLIST_PLAY);
      }
      $('#playListCloseIcon').text('playlist_play');
      $('#btnTogglePlayList').css({
        background: '#3f51b5'
      });
    } else {
      this.controlPlayOrPause(CommonConstant.PLAYLIST_PAUSE);
      $('#playListCloseIcon').text('close');
      $('#btnTogglePlayList').css({
        background: '#f44336'
      });
    }
    $('#btnTogglePlayList').toggleClass('toggle__playlist-close');
    this.initToggler = false;
  }
  fadeVideoControls() {
    var fadeInBuffer = false;
    $(document).mousemove(function() {
      if (!fadeInBuffer) {
        if (this.fadeOutTimer) {
          clearTimeout(this.fadeOutTimer);
          this.fadeOutTimer = 0;
        }
        $('html').css({
          cursor: ''
        });
      } else {
        $('#videoPlayerContainer').css({
          cursor: 'default'
        });
        $('.media-control__container').removeClass('fadeout__controls');
        $('.controls__more').removeClass('fadeout__controls');
        fadeInBuffer = false;
      }
      this.fadeOutTimer = setTimeout(function() {
        if (!this.videoPlayer.paused) {
          $('#videoPlayerContainer').css({
            cursor: 'none'
          });
          $('.media-control__container').addClass('fadeout__controls');
          $('.controls__more').addClass('fadeout__controls');
          fadeInBuffer = true;
        } else {
          fadeInBuffer = false;
        }
      }, 4000);
    });
    $('.media-control__container').css({
      cursor: 'default'
    });
    $('#videoPlayerContainer').css({
      cursor: 'default'
    });
  }
  jumpToDashboard() {
    this.router.navigate(['/dashboard']);
  }
  formatTime(seconds): string {
    if (isNaN(seconds)) {
      return '00:00';
    }
    let minutes = Math.floor(seconds / 60);
    let sMinutes = minutes >= 10 ? minutes : '0' + minutes;
    seconds = Math.floor(seconds % 60);
    let sSeconds = seconds >= 10 ? seconds : '0' + seconds;
    return sMinutes + ':' + sSeconds;
  }
  styleFileBeingViewed() {
    this.removeStyleFileBeingViewed();
    this.addStyleFileBeingViewed();
  }
  removeStyleFileBeingViewed() {
    var self = this;
    if (self.getCourseListFilePlayedCompletelyInd()) {
      $('.file__playing .removePostBlink').text('visibility');
    } else {
      $('.file__playing .removePostBlink').text('visibility_off');
    }
    $('.file__playing').removeClass('file__playing');
  }
  addStyleFileBeingViewed() {
    var fileIndex = this.currentPlayListModel.fileIndex;
    var playListIndex = this.currentPlayListModel.playListIndex;
    this.btnFileBeingViewedId =
      'btnFileVisited_' + playListIndex + '_' + fileIndex;
    this.iconFileBeingViewedId =
      'iconFileNonVisited_' + playListIndex + '_' + fileIndex;
    $('#' + this.btnFileBeingViewedId).addClass('file__playing');
    $('#' + this.iconFileBeingViewedId).text('visibility');
  }
  populateCurrentFileNamePostInit() {
    var fileIndex = this.currentPlayListModel.fileIndex;
    var playListIndex = this.currentPlayListModel.playListIndex;
    this.currentFileName = this.playList[playListIndex].fileContent[
      fileIndex
    ].fileName;
  }
}

<div id="playerContainer">
  <div class="video-player__container" id="videoPlayerContainer">
    <div class='media-control__container' id="playerControls">
      <div>
        <div class="seekbar-slider__container">
          <input type="range" min="1" max="100" value="0" class="seekbar-slider" id="seekbar">
        </div>
        <div id="seekbarTimer"></div>
      </div>
      <div class="controls">
        <!-- <div id="btnPlayPause" class="btn__play-pause" (click)="togglePlayOrPause()">
            <mat-icon id="iconPlayPause" matSuffix>play_arrow</mat-icon>
          </div> -->
        <button id="btnPlayPause" class="btn__play-pause" (click)="controlAction('PLAYLIST_PLAY_PAUSE')" mat-fab color="primary">
          <mat-icon id="iconPlayPause" aria-label="Play or pause">pause</mat-icon>
        </button>
        <!-- <div id="btnPullTimerBack" class="btn__rewind" (click)="rewindCurrentTime()">
            <mat-icon matSuffix>replay_5</mat-icon>
          </div> -->
        <button id="btnPullTimerBack" class="btn__rewind" (click)="controlAction('PLAYLIST_PLAY_PREVIOUS')" mat-fab color="primary">
          <mat-icon aria-label="Rewind 5 seconds">replay_5</mat-icon>
        </button>

        <!-- <div class="playback__rate" id="playBackSpeedBtn">
            <button mat-fab color="primary">1.5</button>
          </div> -->
        <div class="common-dropup">
          <button class="playback__rate" id="playBackSpeedBtn" mat-fab color="primary">1x</button>
          <div class="dropup__container">
            <button class="rate-dropup" (click)="changePlayBackRate(2)" mat-fab color="primary">2x</button>
            <button class="rate-dropup" (click)="changePlayBackRate(1.5)" mat-fab color="primary">1.5x</button>
            <button class="rate-dropup" (click)="changePlayBackRate(1.25)" mat-fab color="primary">1.25x</button>
            <button class="rate-dropup" (click)="changePlayBackRate(1)" mat-fab color="primary">1x</button>
            <button class="rate-dropup" (click)="changePlayBackRate(0.75)" mat-fab color="primary">0.75x</button>
            <button class="rate-dropup" (click)="changePlayBackRate(0.5)" mat-fab color="primary">0.5x</button>
          </div>
        </div>
        <!-- <div class="common-dropup">
            <button class="playback__rate" id="playBackSpeedBtn" mat-fab color="primary">1x</button>
            <div class="dropup__container">
              
            </div>
          </div> -->
        <!-- <div id="btnPullTimerForward" class="btn__forward" (click)="forwardCurrentTime()">
            <mat-icon matSuffix>forward_5</mat-icon>
          </div> -->

        <button id="btnPullTimerForward" class="btn__forward" (click)="controlAction('PLAYLIST_PLAY_NEXT')" mat-fab color="primary">
          <mat-icon aria-label="Rewind 5 seconds">forward_5</mat-icon>
        </button>

        <!-- <button id="btnVolume" class="btn__volume" (click)="controlAction('PLAYLIST_VOLUME')" mat-fab color="primary">
              <mat-icon id="iconMuteUnmute" aria-label="Volume control">volume_up</mat-icon>
            </button> -->

        <div class="common-dropup" id="volumeContainer">
          <button id="btnVolume" class="btn__volume" (click)="controlAction('PLAYLIST_VOLUME')" mat-fab color="primary">
            <mat-icon id="iconMuteUnmute" aria-label="Volume control">volume_up</mat-icon>
          </button>
          <div class="dropup__container volume__dropup-position">
            <input id="volumeControl" class="volume-slider" min="1" max="100" value="36" type="range" orient="vertical" />
          </div>
        </div>

        <!-- <div id="btnFullScreen" class="btn__fullScreen" (click)="toggleFullScreen()">
            <mat-icon id="iconFullScreen" matSuffix>fullscreen</mat-icon>
          </div> -->
        <button id="btnSkipNext" class="btn__skipNext" (click)="playNext()" mat-fab color="primary">
          <mat-icon id="iconSkipNext" aria-label="Rewind 5 seconds">skip_next</mat-icon>
        </button>
        <button id="btnFullScreen" class="btn__fullScreen" (click)="toggleFullScreen()" mat-fab color="primary">
          <mat-icon id="iconFullScreen" aria-label="Rewind 5 seconds">fullscreen</mat-icon>
        </button>

      </div>
    </div>
    <div id="controlActionPerfContainer" class="control__action-container hide">
      <button class="control__action" mat-fab color="primary" (click)="controlAction('PLAYLIST_PLAY_PAUSE')">
        <mat-icon id="iconControlAction"></mat-icon>
      </button>
    </div>
    <video id="videoPlayer" width="100%" height="100%" autoplay>Your browser does not support the video tag. </video>
  </div>

  <div class="side-playlist">
    <app-playlist class="app-playlist" [playList]="playerComponentGlobalData.playList" (onVideoSelection)="initPlaying($event)" (currentPlayListStatus)="toggleCoursePlayListStatus($event)"></app-playlist>
  </div>
  <div class="controls__more" id="headerControls">
    <!-- <div class="toggle__playlist">
          <mat-icon class="toggler-nav__icon" (click)="togglePlayList()">playlist_play</mat-icon>
        </div> -->
    <button id="btnTogglePlayList" class="toggle__playlist toggle__playlist-close" (click)="togglePlayList()" mat-fab color="warn">
      <mat-icon id="playListCloseIcon" aria-label="Rewind 5 seconds">close</mat-icon>
    </button>
    <div class="toggle__playlist-info">
      <mat-chip-list>
        <mat-chip class="mat-chip__file-info" color="primary" selected="true">{{playerComponentGlobalData.currentFileName}}</mat-chip>
      </mat-chip-list>
    </div>
    <!-- <div class="navigate__dashboard">
          <mat-icon class="dashboard-nav__icon" (click)="togglePlayList()">dashboard</mat-icon>
        </div> -->
    <button class="navigate__dashboard" (click)="jumpToDashboard()" mat-fab color="accent">
      <mat-icon aria-label="Rewind 5 seconds">dashboard</mat-icon>
    </button>
  </div>
  <div id="htmlDisplayContainer" class="hide" width="100%" height="100%">
    <div class="htmlDisplayContent" [innerHtml]="playerComponentGlobalData.staticHtml | safeHtml"></div>
  </div>
</div>

<!-- <div class="pdfDisplayContainer">
    <div class="pdfDisplayContent" *ngIf="showPdf">
        <embed src="{{}}" width="600" height="500" alt="pdf">
    </div>
</div> -->

// react-build/src/components/player/player.component.jsx
import React from 'react';

import './player.component.scss';
import { Icon } from '@salilvnair/react-ui';

class Player extends React.Component {
    fadeInBuffer = false;
    fadeOutTimer;
    constructor(props) {
        super(props);
        this.videoElementRef = React.createRef();
        this.seekbarRef = React.createRef();
        this.mediaControlRef = React.createRef();
        this.seekbarTimerRef = React.createRef();
        this.playerContainerRef = React.createRef();
        this.state = {
            playerState: {
                isPaused: false,
                playbackSpeed: "1",
                currentVideoDuration: 0,
                fullScreen: false,
                currentVolume: 50
            }
        }
    }

    metaData = () => {
      let playerMetaData = {
        currentTime : this.videoElementRef.current.currentTime,
        totalDuration : this.videoElementRef.current.duration
      }
      return playerMetaData;
    }

    togglePlayOrPause() {
        const { playerState } = this.state;
        if(playerState.isPaused) {
            this.setState(prevState => ({
                playerState: {
                  ...prevState.playerState,
                  isPaused: false
                }
            }));
            this.videoElementRef.current.play()
        }
        else {
            this.videoElementRef.current.pause();
            this.setState(prevState => ({
                playerState: {
                  ...prevState.playerState,
                  isPaused: true
                }
            }));
        }
    }

    rewindCurrentTime() {
        this.videoElementRef.current.currentTime += -5;
    }

    forwardCurrentTime() {
        this.videoElementRef.current.currentTime += 5;
    }

    handleOnInput  = (event) => {
        var seekBarVal = this.seekbarRef.current.value;
          var vidTime =
          this.videoElementRef.current.duration *
            (seekBarVal / 100);
            this.videoElementRef.current.currentTime = vidTime;
    }

    handleChangeAndMouseMove = (event) => {

        var seekBarVal = (this.seekbarRef.current.value - this.seekbarRef.current.getAttribute('min'))/(this.seekbarRef.current.getAttribute('max')-this.seekbarRef.current.getAttribute('min'));
        var c = this.seekbarRef.current.style;
        c.backgroundImage = '-webkit-gradient(linear, left top, right top, ' +
        'color-stop(' +
        seekBarVal +
        ', #ec5252), ' +
        'color-stop(' +
        seekBarVal +
        ', #818181)' +
        ')';
    }

    handleOnPlay = (event) => {
      if(this.props.playbackSpeed) {
        this.changePlayBackRate(this.props.playbackSpeed);
      }
    }

    handlePlayerOnTimeUpdate = (event) => {
        if (!isNaN(this.videoElementRef.current.duration)) {
            var percentage =
                (this.videoElementRef.current.currentTime /
                this.videoElementRef.current.duration) *
                100;
            this.seekbarRef.current.value = percentage;
            var currentTime =
                this.videoElementRef.current.currentTime;
            var totalDuration =
                this.videoElementRef.current.duration;
            this.seekbarTimerRef.current.innerText = this.formatTime(currentTime) + '/' + this.formatTime(totalDuration);
            var currentVideoDuration = Math.floor(
                this.videoElementRef.current.duration
            );

            this.setState(prevState => ({
                playerState: {
                    ...prevState.playerState,
                    currentVideoDuration: currentVideoDuration
                }
            }));
            this.handleChangeAndMouseMove(event);
        }
    }

    fadeControls = () => {
      console.log('going to fade after 4 secs')
      this.fadeOutTimer = setTimeout(()=>{
        // if (
        //   !self.playerComponentGlobalData.videoPlayer.paused &&
        //   !self.playerComponentGlobalData.isCurrentFileHtml
        // ) {

        // } else {
        //   fadeInBuffer = false;
        // }
        // $('#playerContainer').css({
        //   cursor: 'none'
        // });
        // $('.media-control__container').addClass('fadeout__controls');
        if(this.playerContainerRef.current && this.mediaControlRef.current) {
          this.playerContainerRef.current.style.cursor= 'none';
          this.mediaControlRef.current.classList.add('fadeout__controls');
          this.fadePlaylistControls(true);
          this.fadeInBuffer = true;
        }
      }, 4000)
    }

    componentDidMount() {
      this.fadeVideoControls();
    }

    componentWillUnmount() {
      if (this.fadeOutTimer) {
        clearTimeout(this.fadeOutTimer);
        this.fadeOutTimer = 0;
      }
    }

    fadeVideoControls = () => {
      if (!this.fadeInBuffer) {
        if (this.fadeOutTimer) {
          clearTimeout(this.fadeOutTimer);
          this.fadeOutTimer = 0;
        }
        // $('html').css({
        //   cursor: ''
        // });
      } else {
        if(this.playerContainerRef.current && this.mediaControlRef.current) {
          this.playerContainerRef.current.style.cursor= 'default';
          // .css({
          //   cursor: 'default'
          // });
          this.mediaControlRef.current.classList.remove('fadeout__controls');
          //$('.media-control__container').removeClass('fadeout__controls');
          this.fadePlaylistControls(false);
          this.fadeInBuffer = false;
        }
      }
      this.fadeControls();
    }

    fadePlaylistControls(fade) {
      this.props.fadePlaylistControls(fade);
    }

    changePlayBackRate = (rate) => {
        if(this.videoElementRef.current) {
            this.videoElementRef.current.playbackRate = rate;
            this.setState(prevState => ({
                playerState: {
                    ...prevState.playerState,
                    playbackSpeed:rate+''
                }
            }));
            if(this.props.playBackSpeedChanged) {
              this.props.playBackSpeedChanged(rate);
            }
        }
    }

    formatTime(seconds) {
        if (isNaN(seconds)) {
          return '00:00';
        }
        let minutes = Math.floor(seconds / 60);
        let sMinutes = minutes >= 10 ? minutes : '0' + minutes;
        seconds = Math.floor(seconds % 60);
        let sSeconds = seconds >= 10 ? seconds : '0' + seconds;
        return sMinutes + ':' + sSeconds;
    }

    toggleFullScreen = () => {
        var fullscreenElement =
      document["fullscreenElement"] || document["webkitFullscreenElement"];
      if (fullscreenElement) {
        this.exitFullscreen();
      }
      else {
        this.launchIntoFullscreen(this.playerContainerRef.current);
      }

    }

    launchIntoFullscreen = (element) => {
        if (element.requestFullscreen) {
          element.requestFullscreen();
        } else if (element.mozRequestFullScreen) {
          element.mozRequestFullScreen();
        } else if (element.webkitRequestFullscreen) {
          element.webkitRequestFullscreen();
        } else if (element.msRequestFullscreen) {
          element.msRequestFullscreen();
        }
    }

    exitFullscreen = () => {
        if (document.exitFullscreen) {
          document.exitFullscreen();
        } else if (document["webkitExitFullscreen"]) {
          document["webkitExitFullscreen"]();
        }
    }

    handleVideoEnded() {
        if(this.props.ended) {
            this.props.ended()
        }
    }

    render() {
        const { playerState } = this.state;
        return (
            <div
                id="playerContainer"
                ref={this.playerContainerRef}
                onMouseMove={this.fadeVideoControls}
                className="video-player">
                <video
                    id="videoPlayer"
                    src={this.props.src}
                    ref={this.videoElementRef}
                    onPlay={this.handleOnPlay}
                    onTimeUpdate={this.handlePlayerOnTimeUpdate}
                    onEnded={() => this.handleVideoEnded()}
                    autoPlay>
                </video>
                <div
                  className="media-control__container"
                  ref={this.mediaControlRef}
                  id="playerControls">
                    <div>
                        <div className="seekbar-slider__container">
                            <input
                                type="range"
                                min="1"
                                max="100"
                                defaultValue="0"
                                className="seekbar-slider"
                                id="seekbar"
                                onInput={this.handleOnInput}
                                onChange={this.handleChangeAndMouseMove}
                                onMouseMove={this.handleChangeAndMouseMove}
                                ref={this.seekbarRef} />
                        </div>
                        <div id="seekbarTimer" className="seekbar-timer" ref={this.seekbarTimerRef}></div>
                    </div>
                    <div className="controls">
                        <button id="btnPlayPause" className="btn__play-pause"   onClick={()=>{this.togglePlayOrPause()}}>
                            {
                                playerState.isPaused ?
                                <Icon>play_arrow</Icon>: <Icon>pause</Icon>
                            }
                        </button>
                        <button id="btnPullTimerBack" className="btn__rewind" onClick={()=>{this.rewindCurrentTime()}}>
                            {
                              <Icon>replay_5</Icon>
                            }
                        </button>
                        <div className="common-dropup">
                            <button className="playback__rate" id="playBackSpeedBtn">{playerState.playbackSpeed + 'x'}</button>
                            <div className="dropup__container">
                                <button
                                    className="rate-dropup"
                                    style={
                                        {
                                            background:playerState.playbackSpeed==='2' ? '#ec5252' : 'black'
                                        }
                                    }
                                    onClick={()=>{this.changePlayBackRate(2)}}>
                                        2x</button>
                                <button
                                    className="rate-dropup"
                                    style={
                                        {
                                            background:playerState.playbackSpeed==='1.5' ? '#ec5252' : 'black'
                                        }
                                    }
                                    onClick={()=>{this.changePlayBackRate(1.5)}}>
                                        1.5x</button>
                                <button
                                    className="rate-dropup"
                                    style={
                                        {
                                            background:playerState.playbackSpeed==='1.25' ? '#ec5252' : 'black'
                                        }
                                    }
                                    onClick={()=>{this.changePlayBackRate(1.25)}}>
                                        1.25x</button>
                                <button
                                    className="rate-dropup"
                                    style={
                                        {
                                            background:playerState.playbackSpeed==='1' ? '#ec5252' : 'black'
                                        }
                                    }
                                    onClick={()=>{this.changePlayBackRate(1)}}>
                                        1x</button>
                                <button
                                    className="rate-dropup"
                                    style={
                                        {
                                            background:playerState.playbackSpeed==='0.75' ? '#ec5252' : 'black'
                                        }
                                    }
                                    onClick={()=>{this.changePlayBackRate(0.75)}}>
                                        0.75x</button>
                                <button
                                    className="rate-dropup"
                                    style={
                                        {
                                            background:playerState.playbackSpeed==='0.5' ? '#ec5252' : 'black'
                                        }
                                    }
                                    onClick={()=>{this.changePlayBackRate(0.5)}}>
                                        0.5x</button>
                            </div>
                        </div>
                        <button id="btnPullTimerForward" className="btn__forward" onClick={()=>{this.forwardCurrentTime()}}>
                            {
                                <Icon>forward_5</Icon>
                            }
                        </button>
                        <button
                            id="btnFullScreen"
                            className="btn__fullScreen"
                            onClick={this.toggleFullScreen}  >
                          <Icon>fullscreen</Icon>
                        </button>

                    </div>
                </div>
            </div>
        );
    }
}

export default Player;
